aminos = {
  'UUU': 'Fenilalanina',
  'UUC': 'Fenilalanina',
  'UUA': 'Leucina',
  'UUG': 'Leucina',
  'CUU': 'Leucina',
  'CUC': 'Leucina',
  'CUA': 'Leucina',
  'CUG': 'Leucina',
  'AUU': 'Isoleucina',
  'AUC': 'Isoleucina',
  'AUA': 'Isoleucina',
  'AUG': 'Metionina[Start]',
  'GUU': 'Valina',
  'GUC': 'Valina',
  'GUA': 'Valina',
  'GUG': 'Valina',
  'UCU': 'Serina',
  'UCC': 'Serina',
  'UCA': 'Serina',
  'UCG': 'Serina',
  'CCU': 'Prolina',
  'CCC': 'Prolina',
  'CCA': 'Prolina',
  'CCG': 'Prolina',
  'ACU': 'Treonina',
  'ACC': 'Treonina',
  'ACA': 'Treonina',
  'ACG': 'Treonina',
  'GCU': 'Alanina',
  'GCC': 'Alanina',
  'GCA': 'Alanina',
  'GCG': 'Alanina',
  'UAU': 'Tirosina',
  'UAC': 'Tirosina',
  'UAA': 'Ocre[Stop]',
  'UAG': 'Âmbar[Stop]',
  'CAU': 'Histidina',
  'CAC': 'Histidina',
  'CAA': 'Glutamina',
  'CAG': 'Glutamina',
  'AAU': 'Asparagina',
  'AAC': 'Asparagina',
  'AAA': 'Lisina',
  'AAG': 'Lisina',
  'GAU': 'Ácido aspártico',
  'GAC': 'Ácido aspártico',
  'GAA': 'Ácido glutâmico',
  'GAG': 'Ácido glutâmico',
  'UGU': 'Cisteína',
  'UGC': 'Cisteína',
  'UGA': 'Opala[Stop]',
  'UGG': 'Triptofano',
  'CGU': 'Arginina',
  'CGC': 'Arginina',
  'CGA': 'Arginina',
  'CGG': 'Arginina',
  'AGU': 'Serina',
  'AGC': 'Serina',
  'AGA': 'Arginina',
  'AGG': 'Arginina',
  'GGU': 'Glicina',
  'GGC': 'Glicina',
  'GGA': 'Glicina',
  'GGG': 'Glicina',
}